name: paw_around
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 1.0.2
  flutter_bloc: 8.1.6
  go_router: 14.2.7
  equatable: 2.0.5
  hive_ce: 2.8.0
  hive_ce_flutter: 2.1.0
  provider: 6.1.1
  get_it: 7.6.4
  image_picker: 1.0.7
  path_provider: 2.1.5
  permission_handler: 11.3.1
  google_maps_flutter: 2.14.0
  geolocator: 14.0.2
  http: 1.6.0
  flutter_dotenv: 6.0.0
  url_launcher: 6.3.2
  firebase_core: 4.2.1
  cloud_firestore: 6.1.0
  firebase_auth: 6.1.2
  firebase_storage: 13.0.4
  cached_network_image: 3.4.1
  intl_phone_field: 3.2.0
  pin_code_fields: 8.0.1
  google_sign_in: 6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_ce_generator: ^1.8.0
  build_runner: ^2.4.13
  

flutter:
  uses-material-design: true
  
  assets:
    - assets/intro/
    - assets/auth/
    - assets/home/
    - .env

